### ISSUE TITLE
How would I do variables.

### ISSUE THREAD

**Issue by naterfute** [timonweb/django-tailwind#219]
I can't tell, but it looks like the tailwindcss.config.js file doesn't work properly, maybe I'm just dumb, either way I need some guidense, I need to get some stuff into tailwind, Specifically this and have no idea how too.

colors: {
'text': '#f8ddf9',
'background': '#09020a',
'primary': '#e588e9',
'secondary': '#8f1b48',
'accent': '#dc466a',
},

Help would be much appreciated.

**Comment by tiago-sch** [comment]
Just FYI, I was able to customize my colors by using the 4.1 approach in the CSS file (not sure if you are using v3 or v4). Following the [customize on the docs](https://tailwindcss.com/docs/colors#customizing-your-colors) worked fine for me.

`theme/static_src/src/styles.css`

```css
@import "tailwindcss";

/**
  * A catch-all path to Django template files, JavaScript, and Python files
  * that contain Tailwind CSS classes and will be scanned by Tailwind to generate the final CSS file.
  *
  * If your final CSS file is not being updated after code changes, you may want to broaden or narrow
  * the scope of this path.
  */
@source "../../../**/*.{html,py,js}";

@theme {
  --color-midnight: #121063;
  --color-tahiti: #3ab7bf;
  --color-bermuda: #78dcca;
}
```
